import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Next",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a>Home</a>
          <a>About</a>
          <a>Contact</a>
        </nav>
        {children}
        <footer>hello world this is footer</footer>
      </body>
    </html>
  );
}
export default RootLayout;
